# -*- coding: utf-8 -*-
"""VacuumCleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13khG1ZzyinyjA7YZTpLaS5AiuPybNnFh
"""

import random
def display(room):
  print(room)

room = [[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]]
print("All rooms are dirty")
display(room)

x=0
y=0

while x<4:
  while y<4:
    room[x][y] = random.choice([0,1])
    y+=1
  x+=1
  y=0

print("Before cleaning the room, I detect all these random dirts ")
display(room)


#Itialize counters for cleaning process
x=0
y=0
z=0


#clean room
while x<4:
    while y<4:
        if room[x][y] ==1:
            print("Vacuum in this location now:", x,y)
            room[x][y] = 0
            print("Cleaned: ", x,y)
            z+=1
        y+=1
    x+=1
    y=0
performance = (100 - (( z/16) * 100))
print( "Room is clean now. Thanks for using the robot vaccum cleaner! ")
display(room)
print('Performance= ', performance, '%')